version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: fuses_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
